version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: gymDb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: gymDb
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
