spring:
  application:
    name: 'gym-app'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gymDb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
server:
  port: 8081
service:
  report:
    host: localhost
    port: 8082
amazon:
  sqs:
    queue:
      name: Gym-Main-Report-Queue